spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moxibustion?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    typeAliasesPackage: com/smoxisys/domain
